### PR TITLE
Python3 port

### PR DESCRIPTION
**Pull request by medoc92**
Port to python3, with hopefully minimal modifications.

### CODE REVIEW

**Comment by sandrotosi** [comment]
@dottedmag any plan to look at this PR soon? thanks!

**Comment by sandrotosi** [comment]
i needed also

```
-@@ -245,12 +244,12 @@ class CHMFile:
+@@ -211,6 +210,8 @@ class CHMFile:
+         if self.filename is not None:
+             self.CloseCHM()
+ 
++        archiveName = archiveName.encode()
++
+         self.file = chmlib.chm_open(archiveName)
+         if self.file is None:
+             return 0
+@@ -245,12 +246,12 @@ class CHMFile:
```

other wise i'd get a

```
  File "/usr/lib/python3/dist-packages/chm/chm.py", line 213, in LoadCHM
    self.file = chmlib.chm_open(archiveName)
TypeError: in method 'chm_open', argument 1 of type 'char const *'
```

**Comment by medoc92** [comment]
About the encode() call. This is because you call LoadCHM with an str, the module expect bytes.

I think that the case of calling the method with bytes should be supported, so the conversion should first test if the input is an str instance. Then, the default encoding used by encode() is utf-8, which may not be appropriate for file names on the system, better to use sys.getfilesystemencoding()

Just pushed an update reflecting this.

**Comment by dottedmag** [comment]
I'll have some time to brush the dust off pychm in October, thanks for keeping this branch up-to-date.

**Comment by dottedmag** [comment]
I have just released 0.8.5 with Python 3 support and a bunch of bugfixes. Please check if it works for you. I have tried it on all CHM files I have and it worked.

**Comment by dottedmag** [comment]
@medoc92 I expect to maintain this package from now on, so there is no need anymore to bundle it in `recoll`.

**Comment by medoc92** [comment]
@dottedmag Sure, I'll be glad to unbundle it as soon as the distributions ship with the python3 package.

**Comment by sandrotosi** [comment]
JFTR (as that account has not been deleted) Debian has been shipping a python3 package for pychm for a long time (we're gonna package this new upstream version soon too :) )

**Comment by dottedmag** [comment]
Sure, I saw it. However, there were more bytes/strings fixups needed beyond the patch you've posted on 1 Sep to cover all corner cases, so I'd definitely recommend packaging 0.8.5 ASAP.

**Pull request closed without merging**
